title: Dived By Zero
email: rf3l@pm.me
author: rf3l

description: a place for writting security researchs and i wants to break new bounderias 

theme : minima

base_url: /


twitter_username: x0rg_
github_username:  rf3l

minima:
  date_format: "%Y-%m-%d"

header_pages:
- _pages/about.md
- _pages/index.md

include:
- _pages

exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock
